---
title: "Final Project"
author: "Xinqiao Li"
date: "2025-08-19"
output: html_document
---



```{r}
# Table of summary statistics
meta <- read.csv("QBS103_GSE157103_series_matrix-1.csv", check.names = FALSE)
library(dplyr)

meta_clean <- meta %>%
  dplyr::select(
    ventilator_free_days = `ventilator-free_days`,
    charlson_score,
    age,
    sex,
    icu_status,
    mechanical_ventilation
  ) %>%
  mutate(
    across(c(ventilator_free_days, charlson_score, age),
           ~ suppressWarnings(as.numeric(.)))

  ) %>%
  na.omit()   

str(meta_clean)
head(meta_clean)


```

```{r}
cont_vars <- c("ventilator_free_days", "charlson_score", "age")
cat_vars  <- c("sex", "mechanical_ventilation")

fmt_mean_sd <- function(x) sprintf("%.2f (%.2f)",
                                   mean(x, na.rm = TRUE),
                                   sd(x,   na.rm = TRUE))

for (v in cont_vars) {
  x <- as.numeric(meta_clean[[v]])
  grp <- meta_clean$icu_status
  res <- tapply(x, grp, fmt_mean_sd)
  cat("Variable:", v, "\n")
  print(res)
  cat("\n")
}

for (v in cat_vars) {
  grp <- meta_clean$icu_status
  tab <- table(meta_clean[[v]], grp)
  prop <- prop.table(tab, margin = 2) * 100
  res <- paste0(tab, " (", sprintf("%.1f", prop), "%)")
  
  cat("Variable:", v, "\n")
  print(res)
  cat("\n")
}

```


```{r}
#publication quality
library(ggplot2)
library(tidyverse)
library(tidyr)
setwd("/Users/zaozao/Desktop/Xinqiao")
gene_expression <- read.csv("QBS103_GSE157103_genes.csv", row.names = 1, check.names = FALSE)
meta <- read.csv("QBS103_GSE157103_series_matrix-1.csv", check.names = FALSE)

aass_expression <- as.data.frame(t(gene_expression["AASS", ]))
colnames(aass_expression) <- "AASS"
aass_expression$participant_id <- rownames(aass_expression)

meta$participant_id <- as.character(meta[[1]])

meta_with_aass <- merge(meta, aass_expression, by = "participant_id")

head(meta_with_aass)
dim(meta_with_aass)

```


```{r}
library(ggplot2)
# 1. publication quality histogram
ggplot(meta_with_aass, aes(x = AASS)) +
  geom_histogram(binwidth = 0.01, fill = "yellow", color = "black") +
  labs(title = "Histogram of AASS Gene Expression",
       x = "AASS Expression",
       y = "Count")
```

```{r}
# 2. Scatterplot
meta_with_aass$age <- as.numeric(as.character(meta_with_aass$age))
ggplot(meta_with_aass, aes(x = age, y = AASS)) +
  geom_point(color = "darkgreen") +

  scale_x_continuous(breaks = seq(10, 100, by = 5)) + 
  labs(title = "Scatterplot of AASS Expression vs Age",
       x = "Age",
       y = "AASS Expression")
```

```{r}
# 3. Boxplot

meta_with_aass <- meta_with_aass[meta_with_aass$icu_status != "_id", ]


ggplot(meta_with_aass, aes(x = sex, y = AASS, fill = icu_status)) +
  geom_boxplot() +
  labs(title = "AASS Expression by Sex and ICU Status",
       x = "Sex",
       y = "AASS Expression") +
  theme_minimal()+
  scale_x_discrete(labels = stringr::str_to_title)+
  scale_fill_discrete(labels = stringr::str_to_title, name = "ICU Status")
```


```{r}
library(ggplot2)
library(dplyr)

df <- meta_with_aass %>%
  mutate(AASS = suppressWarnings(as.numeric(AASS))) %>%
  filter(is.finite(AASS))

ggplot(df, aes(x = AASS)) +
  geom_area(stat = "density", fill = "gold", alpha = 0.6, color = "black") +
  labs(
    title = "Distribution of AASS Gene Expression",
    x = "AASS expression",
    y = "Density"
  ) +
  theme_classic(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", hjust = 0),
    axis.title = element_text(face = "bold")
  )


```

```{r}
#heatmap
library(dplyr)
setwd("/Users/zaozao/Desktop/Xinqiao")
gene_expression <- read.csv("QBS103_GSE157103_genes.csv", row.names = 1, check.names = FALSE)
meta <- read.csv("QBS103_GSE157103_series_matrix-1.csv", check.names = FALSE)

selected_genes <- c("AASS", "ABCD1", "ABI2", paste0("ABCA", 1:10))
expr_wide <- as.data.frame(t(gene_expression[selected_genes, , drop = FALSE]))
colnames(expr_wide) <- selected_genes

expr_wide$participant_id <- rownames(expr_wide)
expr_wide <- expr_wide[, c("participant_id", selected_genes)]

meta$participant_id <- colnames(gene_expression)
dataset <- merge(meta, expr_wide, by = "participant_id")

dataset[, selected_genes] <- lapply(dataset[, selected_genes], function(x) as.numeric(as.character(x)))

head(dataset)

```

```{r}
#heatmap
library(dplyr)
library(pheatmap)
library(stringr)


selected_genes <- c("AASS","ABCD1","ABI2", paste0("ABCA", 1:10))
gvar <- apply(gene_expression, MARGIN = 1, FUN = var)
gene_expression2 <- gene_expression[order(gvar, decreasing = TRUE), ]
log2.expr <- log2(gene_expression2 + 1)
mat_log <- log2.expr[selected_genes, , drop = FALSE]
mat_log <- log2.expr[selected_genes, 1:20, drop = FALSE]


ids <- colnames(mat_log)                      
idx <- match(ids, dataset$participant_id)

annotationData <- data.frame(
  row.names  = ids,
  ICU_Status = factor(str_to_title(trimws(dataset$icu_status[idx])),
                      levels = c("No","Yes")),
  Sex        = factor(str_to_title(trimws(dataset$sex[idx])),
                      levels = c("Female","Male","Unknown"))
)

annotationColors <- list(
  ICU_Status = c("No" = "gold", "Yes" = "purple"),
  Sex        = c("Female" = "lightblue", "Male" = "darkgreen", "Unknown" = "grey")
)

pheatmap(mat_log,
         cluster_rows = TRUE, cluster_cols = TRUE,
         clustering_distance_rows = "euclidean",
         clustering_distance_cols = "euclidean",
         annotation_colors = annotationColors,
         annotation_col = annotationData,
         main = "Heatmap (First 20 Samples)",
         border_color = "black",
         show_colnames = TRUE,
         angle_col = 45,          
         fontsize_col = 6,        
         fontsize_row = 8, 
         cellwidth = 10,
         cellheight = 10)

```


